---
all:
  hosts:
    tds-ru-manager-1:
      ansible_host: 5.35.92.30
    tds-ru-worker-1:
      ansible_host: 5.35.92.244
    tds-en-manager-1:
      ansible_host: 167.172.184.117

managers:
  hosts:
    tds-ru-manager-1:
    tds-en-manager-1:

workers:
  hosts:
    tds-ru-worker-1:

ru_swarm:
  hosts:
    tds-ru-manager-1:
    tds-ru-worker-1:
  vars:
    swarm_manager_address: 10.16.1.5

en_swarm:
  hosts:
    tds-en-manager-1:
  vars:
    swarm_manager_address: 10.114.16.2
