---
all:
  hosts:
    nk-router:
      ansible_host: 109.172.46.138
      ansible_python_interpreter: /usr/bin/python3.12
    nk-freedom:
      ansible_host: 104.248.27.206
      ansible_python_interpreter: /usr/bin/python3.12
  vars:
    environment_name: prod
