---
- name: Common configuration
  hosts:
    - all
  vars_files:
    - vars/ssh_accounts.yml
  vars:
    private_lan: 10.16.0.0/16
  roles:
    - role: common
      tags: common
    - role: docker
      tags: docker

- name: Xray RUS
  hosts: nk-router-rus
  vars_files:
    - vars/secrets.yml
  roles:
    - role: xray
      tags: xray
      vars:
        xray_uuid: "{{ secrets.xray_rus.user.uuid }}"
        xray_reality_private_key: "{{ secrets.xray_rus.server.private_key }}"
