---
- name: Common configuration
  hosts: all
  vars_files:
    - vars/main.yml
    - vars/ssh_accounts.yml
  roles:
    - role: common
      tags: common

- name: Postgresql
  hosts: db
  vars_files:
    - vars/main.yml
    - vars/secrets.yml
  roles:
    - role: pg_master
      tags: postgresql

- name: Swarm managers
  hosts: managers
  vars_files:
    - vars/main.yml
    - vars/secrets.yml
  roles:
    - role: swarm_manager
      tags: swarm
