---
- name: Common configuration
  hosts: all
  vars_files:
    - vars/main.yml
    - vars/ssh_accounts.yml
  roles:
    - role: common
      tags: common

- name: RabbitMQ test
  hosts: managers
  vars_files:
    - vars/main.yml
    - vars/secrets.yml
  roles:
    - role: rabbitmq_server
      tags: rabbitmq

# - name: Swarm managers
#   hosts: managers
#   vars_files:
#     - vars/main.yml
#     - vars/secrets.yml
#   roles:
#     - role: swarm_manager
#       tags: swarm
