---
- name: Common configuration
  hosts:
    - all
  vars_files:
    - vars/ssh_accounts.yml
  vars:
    private_lan: 10.16.0.0/16
  roles:
    - role: common
      tags: common
    - role: docker
      tags: docker

- name: Xray RU
  hosts: nk-router-ru
  vars_files:
    - xray/ru/secrets.yml
    - xray/nl/secrets.yml
  vars:
    config_template: "{{ playbook_dir }}/xray/ru/config.json.j2"
    xray_nl_host: "{{ hostvars['nk-xray-nl']['ansible_host'] }}"
  roles:
    - role: xray
      tags: ["xray", "ru"]

- name: Xray NL
  hosts: nk-xray-nl
  vars_files:
    - xray/nl/secrets.yml
  vars:
    config_template: "{{ playbook_dir }}/xray/nl/config.json.j2"
  roles:
    - role: xray
      tags: ["xray", "nl"]
