---
- name: Common configuration
  hosts: all
  vars_files:
    - vars/main.yml
    - vars/ssh_accounts.yml
  roles:
    - role: common
      tags: common

- name: Ru swarm cluster
  hosts: ru_swarm
  vars_files:
    - vars/main.yml
    - vars/secrets.yml
  roles:
    - role: swarm
      tags:
        - swarm
        - ru_swarm

- name: En swarm cluster
  hosts: en_swarm
  vars_files:
    - vars/main.yml
    - vars/secrets.yml
  roles:
    - role: swarm
      tags:
        - swarm
        - en_swarm
