---
- name: Common configuration
  hosts:
    - all
  vars_files:
    - vars/ssh_accounts.yml
  roles:
    - role: common
      tags: common
    - role: docker
      tags: docker

- name: Xray Router
  hosts: nk-router
  vars_files:
    - xray/router/secrets.yml
    - xray/freedom/secrets.yml
  vars:
    config_template: "{{ playbook_dir }}/xray/router/config.json.j2"
    xray_freedom_host: "{{ hostvars['nk-freedom']['ansible_host'] }}"
  roles:
    - role: xray
      tags: ["xray", "router"]

- name: Xray Freedom
  hosts: nk-freedom
  vars_files:
    - xray/freedom/secrets.yml
  vars:
    config_template: "{{ playbook_dir }}/xray/freedom/config.json.j2"
  roles:
    - role: xray
      tags: ["xray", "freedom"]
