---
- name: Common configuration
  hosts:
    - all
  vars_files:
    - vars/ssh_accounts.yml
  vars:
    private_lan: 10.16.0.0/16
  roles:
    - role: common
      tags: common
    - role: docker
      tags: docker
