---
- name: Common configuration
  hosts:
    - all
  vars_files:
    - vars/ssh_accounts.yml
  roles:
    - role: common
      tags: common

- name: Install docker
  hosts:
    - all
  roles:
    - role: docker
      tags: docker
