---
- name: Common configuration
  hosts:
    - all
  vars_files:
    - vars/ssh_accounts.yml
  roles:
    - role: common
      tags: common
    - role: docker
      tags: docker

- name: Configure docker swarm
  hosts:
    - nk-manager-1
  vars_files:
    - vars/secrets.yml
  vars:
    stacks:
      - site-infra
      - backend
  roles:
    - role: swarm
      tags: swarm
