---
- name: Common configuration
  hosts:
    - all
  vars_files:
    - vars/ssh_accounts.yml
  roles:
    - role: common
      tags: common


- name: Hello world with ansible
  hosts:
    - all
  tasks:
    - name: Hello, prod world
      ansible.builtin.debug:
        msg: "Hello, prod world"
