---
- name: Make sure stack directory is present
  file:
    path: /srv/app
    state: directory

- name: Deploy environment files
  template:
    src: env/{{ item }}
    dest: /srv/env/{{ item }}
  loop:
    - app.env

- name: Deploy the app stack
  docker_stack:
    name: app
    resolve_image: never
    with_registry_auth: true
    compose:
      - version: "3.8"
        x-deploy-options: &deploy
          replicas: 1
          update_config:
            parallelism: 2
            delay: 3s
            failure_action: rollback
            order: start-first

        services:
          redis:
            image: redis:7-alpine
            deploy:
              <<: *deploy
            networks:
              - stacknet

          backend:
            image: ghcr.io/fandsdev/cargo-f1/cargo-f1-backend
            env_file:
              - /srv/env/app.env
            environment:
              CACHE_URL: redis://redis:6379/0
            deploy:
              <<: *deploy
            networks:
              - cloudflarenet
              - stacknet

        networks:
          cloudflarenet:
            external: true
          stacknet:
            driver: overlay
            driver_opts:
              com.docker.network.driver.mtu: 1450
