---
name: setup-project
description: 'Setup project: install uv, ansible, ansible-galaxy roles and so on'

runs:
  using: composite

  steps:
    - name: Setup uv
      uses: astral-sh/setup-uv@v7
      with:
        version: '0.9.7'
        enable-cache: true
        cache-dependency-glob: 'uv.lock'

    - name: Setup python
      shell: bash
      run: uv python install

    - name: Cache ansible-galaxy dependencies
      uses: actions/cache@v4
      id: cache-galaxy-dependencies
      with:
        path: |
          ./.ansible
        key: ${{ hashFiles('requirements.yml') }}

    # Always run install. It should be fast enough if dependencies are cached
    - name: Install project dependencies
      shell: bash
      run: make install
